/** STYLE SCOLÉA — Landing éditoriale asymétrique : ivoire, encre, forêt et safran, avec des images de papier imprimé et des CTA concrets. */
import { useState } from 'react';
import { ArrowDownRight, ArrowRight, Check, ChevronDown, Menu, MessageCircle, Search, ShieldCheck, Sparkles, X } from 'lucide-react';
import { BrandMark } from './BrandMark';

const features = [
  { no: '01', title: 'Gestion des élèves', text: 'Ajoutez et retrouvez rapidement chaque élève, sa classe et les coordonnées du parent.', icon: Search },
  { no: '02', title: 'Suivi des frais', text: 'Sachez ce qui est attendu, reçu et reste à récupérer, sans calcul manuel.', icon: ArrowRight },
  { no: '03', title: 'Paiements partiels', text: 'Enregistrez chaque versement reçu et gardez un historique complet par élève.', icon: Check },
  { no: '04', title: 'Filtres intelligents', text: 'Affichez instantanément les payés, partiels ou impayés, par classe ou par recherche.', icon: Sparkles },
  { no: '05', title: 'WhatsApp', text: 'Ouvrez une conversation avec le parent depuis la fiche de l’élève qui doit encore.', icon: MessageCircle },
  { no: '06', title: 'Sécurité & clarté', text: 'Les données de votre établissement restent organisées dans un espace protégé.', icon: ShieldCheck },
];

const faqs = [
  ['Scoléa permet-il de lancer un paiement ?', 'Non. Scoléa est actuellement un outil de suivi. Le directeur enregistre simplement les paiements qu’il a déjà reçus.'],
  ['Peut-on enregistrer un paiement partiel ?', 'Oui. Scoléa additionne les versements et calcule automatiquement le montant restant.'],
  ['Peut-on retrouver les élèves qui doivent encore payer ?', 'Oui. Les filtres Payés, Partiels et Impayés permettent de les retrouver instantanément.'],
  ['Peut-on contacter un parent sur WhatsApp ?', 'Oui. Si un numéro WhatsApp est enregistré, le directeur peut ouvrir une conversation directement depuis la fiche.'],
  ['Scoléa fonctionne-t-il sur téléphone ?', 'Oui. Les parcours essentiels sont conçus pour téléphone, tablette et ordinateur.'],
];

function StatusPill({ status }: { status: 'Payé' | 'Partiel' | 'Impayé' }) {
  const classes = status === 'Payé' ? 'bg-forest/10 text-forest' : status === 'Partiel' ? 'bg-saffron/15 text-[#A85B16]' : 'bg-coral/12 text-[#B64A42]';
  return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[11px] font-extrabold ${classes}`}><span className="h-1.5 w-1.5 rounded-full bg-current" />{status}</span>;
}

function DashboardMockup() {
  const rows = [['Kouassi Jean', '6e 1', '25 000 FCFA', 'Partiel'], ['Awa Traoré', '5e 2', '0 FCFA', 'Payé'], ['Moussa Diallo', '4e 1', '50 000 FCFA', 'Impayé']] as const;
  return (
    <div className="relative ml-auto max-w-[640px] rotate-[1.2deg] rounded-[26px] border border-ink/10 bg-white p-3 shadow-[0_32px_90px_rgba(23,35,31,.17)] sm:p-5">
      <img src="/manus-storage/scolea-hero-editorial_946b5d23.jpg" alt="Bureau de direction scolaire organisé autour d’un registre" className="mb-3 h-28 w-full rounded-2xl object-cover opacity-90 sm:h-36" />
      <div className="flex items-center justify-between border-b border-ink/10 pb-4">
        <div className="flex items-center gap-2"><div className="h-7 w-7 rounded-lg bg-forest/10 p-1.5"><img src="/manus-storage/scolea-mark_192105b7.png" alt="" className="h-full w-full object-contain" /></div><span className="font-display text-xl text-ink">Tableau de bord</span></div>
        <span className="hidden rounded-full bg-ivory px-3 py-1 text-[10px] font-bold uppercase tracking-[.16em] text-ink/50 sm:block">Aujourd’hui · 13 août</span>
      </div>
      <div className="grid grid-cols-3 gap-2 py-4 sm:gap-3">
        {[['642', 'Élèves'], ['18', 'Classes'], ['38', 'Enseignants']].map(([number, label]) => <div key={label} className="rounded-2xl bg-ivory p-3"><div className="font-display text-2xl text-ink sm:text-3xl">{number}</div><div className="mt-1 text-[10px] font-bold uppercase tracking-widest text-ink/45">{label}</div></div>)}
      </div>
      <div className="grid gap-3 sm:grid-cols-[1.1fr_.9fr]">
        <div className="rounded-2xl bg-ink p-4 text-white"><div className="flex items-center justify-between"><span className="text-[10px] font-bold uppercase tracking-[.18em] text-white/55">Situation financière</span><span className="text-saffron">↗ 77%</span></div><div className="mt-5 grid grid-cols-2 gap-3"><div><div className="text-[10px] text-white/45">Total attendu</div><div className="mt-1 text-sm font-extrabold">50 000 000</div></div><div><div className="text-[10px] text-white/45">Encaissé</div><div className="mt-1 text-sm font-extrabold text-saffron">38 500 000</div></div></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full w-[77%] rounded-full bg-saffron" /></div><div className="mt-2 text-[10px] text-white/50">11 500 000 FCFA à récupérer</div></div>
        <div className="rounded-2xl border border-ink/10 bg-white p-4"><div className="text-[10px] font-bold uppercase tracking-[.18em] text-ink/45">Situation des paiements</div><div className="mt-4 space-y-3"><div className="flex items-center justify-between text-xs"><span className="flex items-center gap-2"><i className="h-2 w-2 rounded-full bg-forest" />Payés</span><b>328</b></div><div className="flex items-center justify-between text-xs"><span className="flex items-center gap-2"><i className="h-2 w-2 rounded-full bg-saffron" />Partiels</span><b>147</b></div><div className="flex items-center justify-between text-xs"><span className="flex items-center gap-2"><i className="h-2 w-2 rounded-full bg-coral" />Impayés</span><b>167</b></div></div></div>
      </div>
      <div className="mt-3 overflow-hidden rounded-2xl border border-ink/10"><div className="grid grid-cols-[1.5fr_.8fr_1fr_.8fr] bg-ivory px-4 py-3 text-[9px] font-bold uppercase tracking-widest text-ink/45"><span>Élève</span><span>Classe</span><span>Reste</span><span>Statut</span></div>{rows.map(([name, classroom, amount, status]) => <div key={name} className="grid grid-cols-[1.5fr_.8fr_1fr_.8fr] items-center border-t border-ink/5 px-4 py-3 text-[11px]"><strong className="truncate pr-2">{name}</strong><span className="text-ink/60">{classroom}</span><span className="text-ink/70">{amount}</span><StatusPill status={status} /></div>)}</div>
    </div>
  );
}

export function PublicLanding({ onLogin, onRegister }: { onLogin: () => void; onRegister: () => void }) {
  const [menuOpen, setMenuOpen] = useState(false);
  const [openFaq, setOpenFaq] = useState(0);
  const closeMenu = () => setMenuOpen(false);
  return (
    <div className="min-h-screen overflow-hidden bg-ivory text-ink">
      <header className="fixed inset-x-0 top-0 z-50 border-b border-ink/10 bg-ivory/90 backdrop-blur-xl">
        <div className="mx-auto flex h-[76px] max-w-[1240px] items-center justify-between px-5 lg:px-8"><a href="#accueil" aria-label="Scoléa, accueil"><BrandMark /></a><nav className="hidden items-center gap-8 text-[12px] font-extrabold uppercase tracking-[.1em] text-ink/60 lg:flex"><a href="#fonctionnalites" className="transition-colors hover:text-forest">Fonctionnalités</a><a href="#methode" className="transition-colors hover:text-forest">Comment ça marche</a><a href="#tarifs" className="transition-colors hover:text-forest">Tarifs</a><a href="#faq" className="transition-colors hover:text-forest">FAQ</a></nav><div className="hidden items-center gap-5 lg:flex"><button onClick={onLogin} className="text-sm font-bold text-ink/65 transition hover:text-forest">Se connecter</button><button onClick={onRegister} className="rounded-full bg-forest px-5 py-3 text-sm font-extrabold text-white shadow-[0_10px_25px_rgba(21,91,74,.18)] transition hover:-translate-y-0.5 hover:bg-ink">Commencer gratuitement</button></div><button className="rounded-xl p-2 text-ink lg:hidden" onClick={() => setMenuOpen(v => !v)} aria-label={menuOpen ? 'Fermer le menu' : 'Ouvrir le menu'}>{menuOpen ? <X /> : <Menu />}</button></div>
        {menuOpen && <div className="border-t border-ink/10 bg-ivory px-5 py-5 lg:hidden"><nav className="flex flex-col gap-4 text-sm font-bold"><a href="#fonctionnalites" onClick={closeMenu}>Fonctionnalités</a><a href="#methode" onClick={closeMenu}>Comment ça marche</a><a href="#tarifs" onClick={closeMenu}>Tarifs</a><a href="#faq" onClick={closeMenu}>FAQ</a><button onClick={() => { closeMenu(); onLogin(); }} className="border-t border-ink/10 pt-4 text-left">Se connecter</button><button onClick={() => { closeMenu(); onRegister(); }} className="rounded-full bg-forest px-5 py-3 text-left text-white">Commencer gratuitement</button></nav></div>}
      </header>

      <main id="accueil">
        <section className="relative mx-auto grid max-w-[1240px] gap-12 px-5 pb-20 pt-36 lg:grid-cols-[.82fr_1.18fr] lg:items-center lg:px-8 lg:pb-28 lg:pt-48"><div className="absolute -left-32 top-32 h-80 w-80 rounded-full bg-saffron/10 blur-3xl" /><div className="relative"><div className="mb-6 flex items-center gap-3 text-[11px] font-extrabold uppercase tracking-[.2em] text-forest"><span className="h-px w-8 bg-saffron" />Le cahier de pilotage des écoles</div><h1 className="max-w-xl font-display text-[clamp(3.5rem,6vw,6.6rem)] leading-[.88] tracking-[-.045em] text-ink">Gérez votre école <em className="text-forest">simplement.</em></h1><p className="mt-8 max-w-lg text-lg leading-relaxed text-ink/65">Scoléa vous aide à gérer vos élèves et à suivre les frais scolaires depuis une seule plateforme claire, rapide et rassurante.</p><div className="mt-9 flex flex-wrap items-center gap-3"><button onClick={onRegister} className="group inline-flex items-center gap-3 rounded-full bg-forest px-6 py-4 text-sm font-extrabold text-white shadow-[0_15px_35px_rgba(21,91,74,.2)] transition hover:-translate-y-1 hover:bg-ink">Commencer gratuitement <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" /></button><a href="#fonctionnalites" className="inline-flex items-center gap-2 rounded-full border border-ink/15 px-6 py-4 text-sm font-extrabold text-ink transition hover:border-forest hover:text-forest">Découvrir Scoléa <ArrowDownRight className="h-4 w-4" /></a></div><div className="mt-9 flex items-center gap-3 text-xs font-semibold text-ink/50"><span className="flex -space-x-2"><span className="grid h-7 w-7 place-items-center rounded-full border-2 border-ivory bg-forest text-[10px] font-extrabold text-white">D</span><span className="grid h-7 w-7 place-items-center rounded-full border-2 border-ivory bg-saffron text-[10px] font-extrabold text-white">C</span><span className="grid h-7 w-7 place-items-center rounded-full border-2 border-ivory bg-ink text-[10px] font-extrabold text-white">S</span></span><span>Pour les directeurs, secrétaires et comptables d’établissement</span></div></div><div className="relative"><div className="absolute -right-16 -top-16 hidden h-52 w-52 rounded-full border border-saffron/30 lg:block" /><div className="absolute -bottom-8 -left-8 z-10 hidden rounded-2xl bg-saffron px-5 py-4 text-ink shadow-xl sm:block"><div className="text-[10px] font-extrabold uppercase tracking-widest">À récupérer</div><div className="mt-1 font-display text-2xl">11 500 000 <small className="font-sans text-xs font-bold">FCFA</small></div></div><DashboardMockup /></div></section>

        <section className="border-y border-ink/10 bg-white"><div className="mx-auto grid max-w-[1240px] gap-6 px-5 py-8 text-sm font-bold text-ink/55 sm:grid-cols-3 lg:px-8"><div className="flex items-center gap-3"><span className="text-saffron">01</span><span>Élèves et classes au même endroit</span></div><div className="flex items-center gap-3"><span className="text-saffron">02</span><span>Solde calculé automatiquement</span></div><div className="flex items-center gap-3"><span className="text-saffron">03</span><span>Le paiement reste hors de Scoléa</span></div></div></section>

        <section id="fonctionnalites" className="mx-auto max-w-[1240px] px-5 py-24 lg:px-8 lg:py-32"><div className="grid gap-14 lg:grid-cols-[.62fr_1.38fr]"><div><div className="eyebrow">Pourquoi Scoléa</div><h2 className="mt-5 max-w-md font-display text-5xl leading-[.95] tracking-[-.04em] sm:text-6xl">Le calme après la feuille de calcul.</h2><p className="mt-6 max-w-sm leading-relaxed text-ink/60">Retrouvez une information en quelques secondes. Une situation financière lisible commence par un registre bien tenu.</p><a href="#methode" className="mt-7 inline-flex items-center gap-2 text-sm font-extrabold text-forest">Voir la méthode <ArrowRight className="h-4 w-4" /></a></div><div className="grid gap-x-10 gap-y-0 sm:grid-cols-2">{features.map(({ no, title, text, icon: Icon }) => <div key={no} className="group border-t border-ink/12 py-7"><div className="flex items-start justify-between"><span className="font-mono text-xs font-bold text-saffron">{no}</span><Icon className="h-5 w-5 text-forest/45 transition group-hover:text-forest" /></div><h3 className="mt-7 font-display text-2xl">{title}</h3><p className="mt-2 max-w-xs text-sm leading-relaxed text-ink/58">{text}</p></div>)}</div></div></section>

        <section id="methode" className="bg-forest text-white"><div className="mx-auto grid max-w-[1240px] gap-14 px-5 py-24 lg:grid-cols-[.85fr_1.15fr] lg:items-center lg:px-8 lg:py-32"><div><div className="eyebrow text-saffron">Une méthode sans détour</div><h2 className="mt-5 max-w-lg font-display text-5xl leading-[.95] tracking-[-.04em] sm:text-6xl">Du reçu reçu au solde compris.</h2><p className="mt-6 max-w-md text-white/65 leading-relaxed">Le parent paie en dehors de Scoléa. Vous enregistrez ensuite le montant réellement reçu : le total, le reste et le statut se mettent à jour automatiquement.</p><div className="mt-8 flex items-center gap-3 text-sm font-bold text-white/75"><span className="h-2 w-2 rounded-full bg-saffron" />Aucun bouton « Payer maintenant » dans l’application.</div></div><div className="relative"><img src="/manus-storage/scolea-workflow_3acd2cc3.jpg" alt="Illustration du suivi d’un paiement reçu et d’un solde scolaire" className="w-full rounded-[28px] object-cover shadow-2xl" /><div className="absolute -bottom-5 -left-5 rounded-2xl border border-white/15 bg-ink px-5 py-4 shadow-xl"><div className="text-[10px] font-extrabold uppercase tracking-widest text-white/45">Statut automatique</div><div className="mt-1 flex items-center gap-2 font-display text-xl"><span className="h-2.5 w-2.5 rounded-full bg-saffron" />Partiellement payé</div></div></div></div></section>

        <section className="mx-auto max-w-[1240px] px-5 py-24 lg:px-8 lg:py-32"><div className="flex flex-col justify-between gap-7 border-b border-ink/12 pb-8 sm:flex-row sm:items-end"><div><div className="eyebrow">Le quotidien, en quatre gestes</div><h2 className="mt-5 max-w-2xl font-display text-5xl leading-[.95] tracking-[-.04em] sm:text-6xl">Une routine qui laisse de la place à l’école.</h2></div><span className="font-mono text-xs text-ink/40">Scoléa / 04 étapes</span></div><div className="grid gap-8 pt-10 sm:grid-cols-2 lg:grid-cols-4">{[['01', 'Ajoutez vos élèves', 'Classe, matricule, parent et frais scolaires : tout est réuni dans une fiche.'], ['02', 'Enregistrez les paiements reçus', 'Le paiement se fait en dehors de Scoléa. Vous consignez simplement le montant reçu.'], ['03', 'Scoléa calcule automatiquement', 'Le total payé, le reste et le statut sont mis à jour sans calcul manuel.'], ['04', 'Contactez les parents', 'S’il reste un solde, le numéro WhatsApp est accessible depuis la fiche élève.']].map(([number, title, text]) => <div key={number}><div className="font-mono text-sm font-bold text-saffron">{number}</div><h3 className="mt-10 font-display text-2xl leading-tight">{title}</h3><p className="mt-3 text-sm leading-relaxed text-ink/58">{text}</p></div>)}</div></section>

        <section className="border-y border-ink/10 bg-[#EDE9DF]"><div className="mx-auto grid max-w-[1240px] gap-14 px-5 py-24 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:px-8 lg:py-28"><div className="order-2 lg:order-1"><img src="/manus-storage/scolea-whatsapp_cf69d08c.jpg" alt="Illustration d’un contact WhatsApp depuis une fiche élève" className="w-full rounded-[28px] object-cover shadow-[0_22px_50px_rgba(23,35,31,.12)]" /></div><div className="order-1 lg:order-2"><div className="eyebrow">Relancer sans chercher</div><h2 className="mt-5 max-w-lg font-display text-5xl leading-[.95] tracking-[-.04em] sm:text-6xl">Le bon numéro, au bon moment.</h2><p className="mt-6 max-w-md text-lg leading-relaxed text-ink/62">Un parent doit encore payer ? Retrouvez son numéro WhatsApp directement depuis la fiche de l’élève et ouvrez la conversation avec un message préparé.</p><div className="mt-8 rounded-2xl border border-ink/10 bg-white p-5"><div className="flex items-start justify-between"><div><div className="font-display text-xl">Kouassi Jean</div><div className="mt-1 text-xs font-bold uppercase tracking-widest text-ink/45">6e 1 · 2026001</div></div><span className="rounded-full bg-coral/12 px-3 py-1 text-[11px] font-extrabold text-[#B64A42]">Impayé</span></div><div className="mt-5 grid grid-cols-3 gap-3 border-t border-ink/8 pt-4 text-xs"><div><div className="text-ink/45">Frais</div><strong>50 000</strong></div><div><div className="text-ink/45">Payé</div><strong>0</strong></div><div><div className="text-ink/45">Reste</div><strong className="text-coral">50 000</strong></div></div><button onClick={onRegister} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-forest py-3 text-sm font-extrabold text-white">Contacter sur WhatsApp <MessageCircle className="h-4 w-4" /></button></div></div></div></section>

        <section className="mx-auto max-w-[1240px] px-5 py-24 lg:px-8 lg:py-32"><div className="grid gap-14 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><div><div className="eyebrow">Voir avant de décider</div><h2 className="mt-5 max-w-md font-display text-5xl leading-[.95] tracking-[-.04em] sm:text-6xl">Votre établissement, sur une seule page.</h2><p className="mt-6 max-w-md leading-relaxed text-ink/60">Une vue simple de la situation financière, des classes à suivre et des élèves à relancer. Les chiffres ne demandent pas d’interprétation.</p><button onClick={onRegister} className="mt-8 inline-flex items-center gap-3 rounded-full bg-saffron px-6 py-4 text-sm font-extrabold text-ink transition hover:-translate-y-1 hover:bg-[#ef9a46]">Ouvrir mon espace <ArrowRight className="h-4 w-4" /></button></div><div className="relative"><img src="/manus-storage/scolea-school-collage_058fc438.jpg" alt="Illustration éditoriale d’un établissement scolaire organisé" className="h-[360px] w-full rounded-[28px] object-cover lg:h-[470px]" /><div className="absolute bottom-5 left-5 max-w-[250px] rounded-2xl bg-ivory/95 p-4 shadow-xl backdrop-blur"><div className="font-display text-xl">Simple. Rapide. Clair.</div><div className="mt-1 text-xs leading-relaxed text-ink/55">Élèves et frais scolaires au même endroit.</div></div></div></div></section>

        <section id="tarifs" className="bg-ink text-white"><div className="mx-auto max-w-[1240px] px-5 py-24 lg:px-8 lg:py-32"><div className="max-w-xl"><div className="eyebrow text-saffron">Des formules à votre mesure</div><h2 className="mt-5 font-display text-5xl leading-[.95] tracking-[-.04em] sm:text-6xl">Commencez par l’essentiel.</h2><p className="mt-6 text-white/60">Les tarifs seront précisés avec les premiers établissements partenaires. La structure est prête à évoluer avec la taille de votre école.</p></div><div className="mt-14 grid gap-4 lg:grid-cols-3">{[['Démarrage', 'Pour les petites écoles', 'Jusqu’à 200 élèves'], ['Pro', 'Pour les établissements en croissance', 'Jusqu’à 800 élèves'], ['Établissement', 'Pour les grandes écoles', 'Élèves illimités']].map(([title, subtitle, limit], index) => <div key={title} className={`rounded-[22px] border p-6 ${index === 1 ? 'border-saffron bg-saffron text-ink' : 'border-white/15 bg-white/5'}`}><div className="flex items-center justify-between"><h3 className="font-display text-2xl">{title}</h3>{index === 1 && <span className="rounded-full bg-ink px-2.5 py-1 text-[9px] font-extrabold uppercase tracking-widest text-white">Populaire</span>}</div><p className={`mt-2 text-sm ${index === 1 ? 'text-ink/65' : 'text-white/55'}`}>{subtitle}</p><div className="mt-8 border-t border-current/15 pt-5 text-sm font-bold">{limit}</div><ul className={`mt-5 space-y-3 text-sm ${index === 1 ? 'text-ink/70' : 'text-white/65'}`}><li className="flex gap-2"><Check className="h-4 w-4 shrink-0" />Gestion des élèves</li><li className="flex gap-2"><Check className="h-4 w-4 shrink-0" />Suivi des frais et historiques</li><li className="flex gap-2"><Check className="h-4 w-4 shrink-0" />Filtres et relance WhatsApp</li></ul><button onClick={onRegister} className={`mt-8 w-full rounded-xl py-3 text-sm font-extrabold ${index === 1 ? 'bg-ink text-white' : 'bg-white text-ink'}`}>Commencer</button></div>)}</div></div></section>

        <section id="faq" className="mx-auto max-w-[920px] px-5 py-24 lg:py-32"><div className="text-center"><div className="eyebrow justify-center">Questions fréquentes</div><h2 className="mt-5 font-display text-5xl leading-[.95] tracking-[-.04em] sm:text-6xl">Les réponses, sans petites lignes.</h2></div><div className="mt-12 border-t border-ink/12">{faqs.map(([question, answer], index) => <div key={question} className="border-b border-ink/12"><button className="flex w-full items-center justify-between gap-6 py-6 text-left font-display text-xl" onClick={() => setOpenFaq(openFaq === index ? -1 : index)}>{question}<ChevronDown className={`h-5 w-5 shrink-0 text-forest transition-transform ${openFaq === index ? 'rotate-180' : ''}`} /></button>{openFaq === index && <p className="max-w-2xl pb-6 pr-10 leading-relaxed text-ink/60">{answer}</p>}</div>)}</div></section>

        <section className="mx-auto max-w-[1240px] px-5 pb-24 lg:px-8 lg:pb-32"><div className="grid gap-4 lg:grid-cols-2"><div className="rounded-[26px] border border-ink/10 bg-white p-7 sm:p-9"><div className="eyebrow">Paroles de directeurs</div><h2 className="mt-5 font-display text-4xl leading-none">Votre expérience pourra trouver sa place ici.</h2><p className="mt-5 max-w-md text-sm leading-relaxed text-ink/58">Nous publierons uniquement des témoignages réels, avec l’accord des directeurs et responsables d’établissement. Aucun avis n’est inventé.</p><div className="mt-8 rounded-2xl border border-dashed border-ink/15 bg-[#F9F7F2] p-5 text-sm font-bold text-ink/45">Emplacement réservé à un témoignage vérifié</div></div><div className="rounded-[26px] bg-forest p-7 text-white sm:p-9"><div className="eyebrow text-saffron">Une identité à construire ensemble</div><h2 className="mt-5 font-display text-4xl leading-none">Le registre devient plus utile quand il reflète votre quotidien.</h2><p className="mt-5 max-w-md text-sm leading-relaxed text-white/60">Scoléa commence par les fondamentaux : une fiche élève fiable, un solde juste et un historique que toute l’équipe peut comprendre.</p><div className="mt-8 flex items-center gap-3 text-sm font-extrabold text-saffron"><span className="h-2 w-2 rounded-full bg-saffron" />Pensé pour les écoles en mouvement</div></div></div></section>
        <section className="mx-5 mb-8 overflow-hidden rounded-[30px] bg-saffron lg:mx-auto lg:max-w-[1240px]"><div className="relative px-6 py-16 sm:px-12 lg:px-20 lg:py-20"><div className="absolute -right-12 -top-24 h-64 w-64 rounded-full border-[32px] border-ink/10" /><div className="relative max-w-2xl"><div className="eyebrow text-ink/65">Un registre plus clair commence ici</div><h2 className="mt-5 font-display text-5xl leading-[.92] tracking-[-.04em] text-ink sm:text-7xl">Prêt à simplifier la gestion de votre école ?</h2><p className="mt-6 max-w-lg text-lg text-ink/65">Commencez à gérer vos élèves et vos frais scolaires avec Scoléa.</p><button onClick={onRegister} className="mt-8 inline-flex items-center gap-3 rounded-full bg-ink px-6 py-4 text-sm font-extrabold text-white transition hover:-translate-y-1">Commencer gratuitement <ArrowRight className="h-4 w-4" /></button></div></div></section>
      </main>

      <footer className="border-t border-ink/10 bg-ivory"><div className="mx-auto grid max-w-[1240px] gap-10 px-5 py-12 lg:grid-cols-[1fr_auto] lg:px-8"><div><BrandMark /><p className="mt-4 max-w-xs text-sm leading-relaxed text-ink/55">La gestion scolaire, simplement. Élèves et frais scolaires au même endroit.</p><p className="mt-7 text-xs text-ink/38">© 2026 Scoléa. Les informations de contact seront ajoutées prochainement.</p></div><nav className="grid grid-cols-2 gap-x-12 gap-y-4 text-sm font-bold text-ink/55"><a href="#fonctionnalites">Fonctionnalités</a><a href="#tarifs">Tarifs</a><a href="#faq">FAQ</a><button className="text-left" onClick={onLogin}>Connexion</button><button className="text-left" onClick={onRegister}>Inscription</button><a href="#accueil">Confidentialité</a></nav></div></footer>
    </div>
  );
}
